name: Linting
on: [ push, pull_request ]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
        poetry-version: [ "1.3.2" ]
        os: [ ubuntu-18.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Black
        run: poetry run black --check .

      - name: Isort
        run: poetry run isort --check-only .

      - name: Ruff
        run: poetry run ruff check .

      - name: Mypy
        run: poetry run mypy .
